### ISSUE TITLE
HelloWorld on the hosting

### ISSUE THREAD

**Issue by acrm** [EkaSe/CoffeeToCode#1]
1. On hosting:
- [x] Get trial hosting
- [x] Get FTP settings
- [ ] Check out your default site (Account  Page -> Login CP -> My Sites -> Site1 -> ```yourlogin-001-site1.htempurl.com```)
2. In VS Code:
- [x] Install ftp-sync plugin
- [x] Set FTP settings (F1 + Ftp-sync: Init)
- [x] Download site content to local directory (F1 + Ftp-sync: Remote to local)
- [x] Change in ```Default.asp``` body content to "Hello World" or something else
- [x] Upload updated file to hosting (F1 + Ftp-sync: Local to remote)
3. In Hosting:
- [x] Check out the ```yourlogin-001-site1.htempurl.com``` again

**Comment by EkaSe** [comment]
semiash-001-site1.dtempurl.com

**Comment by acrm** [comment]
Good)
