### ISSUE TITLE
Exploring dynamic pages: run-time compiled executables

### ISSUE THREAD

**Issue by acrm** [EkaSe/CoffeeToCode#5]
What is good in pre-compiled executables? 
* We combine static and dynamic part for the same page in one source file 
* We separate logic of one page from another 

But what drawbacks we get with this approach? 
* Extra spend of system resources: for each page we need at least one extra process of operational system, with dedicated memory address space, system handlers and other pricy resources. 
* Extra development infrastructure: for each page we need besides the source file itself also a project file, etc. 
* More development routine: after any changes in any page's source we have to recompile corresponding project 

Any ideas how to overcome these disadvantages, keeping all benefits?

**Comment by EkaSe** [comment]
@acrm Why don't we have classes for each page inside our project instead of having separate applications?

**Comment by EkaSe** [comment]
@acrm Then I can imagine some perversion like reading and invoking the code from existing string or text file. Another variant is to have some predefined text files with HTML and certain marks (code-like expressions?) inside that can be parsed and interpreted by our webserver in order to obtain correct HTML with real-time generated data

**Comment by acrm** [comment]
You anticipate our next step) That's right, let's start from code files, that will be compiled right in runtime, and invoked immediately. 

You can start with that example: [Runtime compilation](https://www.codeproject.com/Tips/715891/Compiling-Csharp-Code-at-Runtime)

**Comment by EkaSe** [comment]
@acrm 
I used http://www.tugberkugurlu.com/archive/compiling-c-sharp-code-into-memory-and-executing-it-with-roslyn instead of CodeDom (.Net Core dislikes CodeDom - see https://github.com/dotnet/corefx/issues/12180).
